// /lib/types.ts

export type EventType =
  | 'login'
  | 'view_balance'
  | 'add_payee'
  | 'transfer'
  | 'change_password'
  | 'request_flood';

export type Verdict = 'allow' | 'soft_challenge' | 'hard_challenge' | 'block';

export type Layer = 'network' | 'behavioral' | 'transactional';

export interface Signal {
  name: string;
  layer: Layer;
  weight: number;
  reason: string;
}

export interface UserBaseline {
  userId: string;
  name: string;
  usualIPs: string[];
  usualASNs: string[];
  usualCountry: string;
  usualDevices: string[];
  usualUserAgent: string;
  avgTransferAmount: number;
  stdTransferAmount: number;
  knownPayees: string[];
  typicalTypingSpeedMs: number;
}

/**
 * sealStatus is server-computed after validating the cryptographic telemetry seal.
 * The browser SDK signs every payload with a single-use nonce; direct API callers
 * (e.g. attacker console) have no valid nonce and are flagged immediately.
 *
 *  valid    — nonce consumed, SHA-256 seal matches server recomputation
 *  missing  — no challengeNonce or telemetrySeal in payload (direct API call)
 *  expired  — nonce older than 30 s (possible replay of captured payload)
 *  reused   — nonce already consumed (definite replay attack)
 *  forged   — nonce not issued by this server (crafted or cross-server)
 *  tampered — nonce valid but seal hash mismatch (fields altered after signing)
 */
export type SealStatus = 'valid' | 'missing' | 'expired' | 'reused' | 'forged' | 'tampered';

export interface SentinelEvent {
  id?: string;
  userId: string;
  type: EventType;
  timestamp?: number;
  ip: string;
  country?: string;
  geoCountry?: string;
  geoCity?: string;
  asn?: string;
  userAgent: string;
  deviceFingerprint: string;
  inputMethod?: 'typed' | 'pasted' | 'autofill';
  amount?: number;
  payeeId?: string;
  payeeName?: string;
  isKnownPayee?: boolean;
  requestRateLastMinute?: number;
  attackScenario?: string;
  typingSpeedMs?: number;
  mouseMovementScore?: number;
  precedingEvents?: string[];
  // Cryptographic telemetry seal — set by the browser SDK, validated server-side
  challengeNonce?: string;
  telemetrySeal?: string;
  // Injected by /api/events route after seal validation — never trusted from client
  sealStatus?: SealStatus;
}

export interface RiskAssessment {
  eventId: string;
  score: number;
  verdict: Verdict;
  signals: Signal[];
  latencyMs: number;
  /**
   * Plain-language action instruction for the SOC analyst — generated by the
   * scorer from the verdict + dominant signals so no manual interpretation is needed.
   * Removes the "read 7 signals and figure out what to do" workload from the analyst.
   */
  recommendation: string;
  overridden?: boolean;
  overrideNote?: string;
}

// ProcessedEvent is what gets stored and streamed — combines raw event + assessment
export type ProcessedEvent = SentinelEvent & RiskAssessment;
